# Generated by Django 4.2.4 on 2023-08-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertis',
            table='advertisements',
        ),
    ]
