# Generated by Django 4.2.4 on 2023-08-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_advertisemen'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisemen',
            table='adv',
        ),
    ]
