# Generated by Django 4.2.4 on 2023-08-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_advertisemen_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisemen',
            table='advertisement',
        ),
    ]
